@startuml Metodo Regla Falsa

left to right direction

actor Usuario as U
rectangle "Aplicacion" as App {
    usecase "Ingresar Intervalo" as UC1
    usecase "Tabular Funcion" as UC2
    usecase "Calcular Raiz" as UC3
    UC1 --> UC2
    UC2 --> UC3
    U --> UC1
    U --> UC3
}

@enduml
