@startuml Regla Falsa
class ReglaFalsa {
  - a: double
  - b: double
  - tolerancia: double
  - xr: double
  - xa: double
  + ReglaFalsa(a: double, b: double, tolerancia: double)
  + tabula(): void
  + calcularRaiz(): void
  + f(x: double): double
  - mostrarTablaEncabezado(): void
  - mostrarIteracion(a: double, b: double, xr: double, fa: double, fb: double, fc: double, error: double): void
}

ReglaFalsa --> "colors.h"
ReglaFalsa --> "ReglaFalsa.h"

@enduml